# ─────────────────────────────────────────────────────────────────────
#  「✦ HYPERPAPER CONFIG ✦ 」
# ─────────────────────────────────────────────────────────────────────

# ── WALLPAPER ────────────────────────────────────────────────────────
wallpaper {
    monitor =
    path = ~/walls/image.png
}

# ── GENERAL ──────────────────────────────────────────────────────────
splash = false
ipc = on
