# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D9D6E1
background         #29262B
cursor             #9D96A9

active_tab_foreground     #29262B
active_tab_background     #D9D6E1
inactive_tab_foreground   #D9D6E1
inactive_tab_background   #29262B

active_border_color   #D9D6E1
inactive_border_color #29262B
bell_border_color     #3D3346

color0      #4F4C50
color1		#3D3346
color2		#494054
color3		#554D62
color4		#625A71
color5		#6E677F
color6		#6E677F
color7		#C0BCCC
color8		#87838E
color9		#51445E
color10		#615570
color11		#726783
color12		#827896
color13		#9389A9
color14		#9389A9
color15		#C0BCCC
