# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3EAEB
background         #30302E
cursor             #AFBBB5

active_tab_foreground     #30302E
active_tab_background     #E3EAEB
inactive_tab_foreground   #E3EAEB
inactive_tab_background   #30302E

active_border_color   #E3EAEB
inactive_border_color #30302E
bell_border_color     #24241D

color0      #545452
color1		#24241D
color2		#5C685E
color3		#446B81
color4		#486E82
color5		#849395
color6		#849395
color7		#CFD9DA
color8		#919899
color9		#303027
color10		#7B8B7E
color11		#5B8FAC
color12		#6092AE
color13		#B0C4C7
color14		#B0C4C7
color15		#CFD9DA
